version: 0.0
os: linux
files:
  - source: build/libs/matal-server-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/backend
    overwrite: yes
  - source: appspec.yml
    destination: /home/ubuntu/backend/
    overwrite: yes
  - source: scripts
    destination: /home/ubuntu/backend/
    overwrite: yes
  - source: src/main/resources/logback-spring.xml
    destination: /home/ubuntu/backend/
    overwrite: yes
  - source: src/main/resources/warn-appender.xml
    destination: /home/ubuntu/backend/
    overwrite: yes
  - source: src/main/resources/error-appender.xml
    destination: /home/ubuntu/backend/
    overwrite: yes
  - source: src/main/resources/info-appender.xml
    destination: /home/ubuntu/backend/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 240
      runas: ubuntu
